### ISSUE TITLE
FarmArk: Make a "Blogs" Page with Blog Cards

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#10]
Hey Hacktoberfest participants, good to see you.

Build a FarmArk Blog Page with multiple cards that have some text block and accompanying images. Follow the following as a part of your checklist.

- Make sure that the images you use are uncopyrighted (Some sources are [Pexels](https://www.pexels.com/), [Pixabay](https://pixabay.com/), [Unsplash](https://unsplash.com/images) ).
- Use FarmArk relevant text and images (feel free to use your creativity)
- Make sure that Blog is linked in all correct places (navbar, footer, etc.)

Feel free to use the below link as a reference:
[Blog Top 50](https://detailed.com/50/)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by Aankirz** [comment]
Can you please assign this to me

**Comment by Aankirz** [comment]
@Isha307 pls assign this to me

**Comment by Isha307** [comment]
@Aankirz Assigned to you 👍
