### ISSUE TITLE
FarmArk: Add farming themed carousel to homepage

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#11]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to create a farming themed carousel to homepage

Add a farming-themed carousel to index.html. Make sure you use uncopyrighted images. Use 4-5 slides in the carousel, heroing different FarmArk features. Feel free to use below reference:

[Texhnext](https://technext.github.io/montana/index.html)

How to get it approved?

- Add a screenshot of  outlook on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by Isha307** [comment]
Yes @Aankirz, but please explain your approach first.

**Comment by Aankirz** [comment]
I'll add the carousel as shown in your example https://technext.github.io/montana/index.html
into inex.html highlighting features of farmark

**Comment by Isha307** [comment]
@Aankirz Assigned to you.

**Comment by Aankirz** [comment]
Can you please give me the list of features(not written in readme) or should I just write a dummy data?

**Comment by Aankirz** [comment]
Hey @Isha307 it's done can you please review my pr
