### ISSUE TITLE
FarmArk : Crop Recommendation System

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#17]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to find the best correct crops for their soil and environment conditions. When selecting it should take you to GUI where user enters the various soil and environmental conditions and submitting would provide you with 3 most suitable crops for their soil and environment.

View the conditions in which crops are grown : If the user clicks on this button, they are presented with a screen in which they can select the condition (Nitrogen, Phosphorus, temperature, humidity, pH, or rainfall) which they want to observe. After the selection is made, the user is presented with a plot that displays the crops (y-axis) versus condition with the respective unit (x-axis). This allows the user to identify the various ranges in which the various crops can grow. 

How to get it approved?

- Add the details of how you had done then wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by theshredbox** [comment]
Ma'am I would like to take this issue as a contribution for Hacktoberfest '22.
Name- Aryan Ahuja
Hacktoberfest Participant
Type- Documentation
Approach- Use Crop Recommendation dataset, perform feature extraction, and train ML models to make predictions based on user input

**Comment by prathimacode-hub** [comment]
Issue assigned to @theshredbox
