### ISSUE TITLE
FarmArk : Create a Header Section of Home Page 

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#7]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to create a header section of home page which also includes Navigation bar of farming webapp

Feel free to be creative! And please take care of the following criteria:

- create header along with Navigation Bar with 6 options
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of  header on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by muskan467** [comment]
I want to work on this issue

**Comment by Isha307** [comment]
> I want to work on this issue

Okay @muskan467, Please tell me your approach and the tech stacks you will use. Then Only I can assign it to you.

**Comment by muskan467** [comment]
@Isha307 I will use bootstrap navbar class to design the header and also place the logo with the website name.

**Comment by prathimacode-hub** [comment]
@muskan467. Issue assigned to you.
