### ISSUE TITLE
FarmArk : Create a Footer Section for the Home Page

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#8]
Hey Hacktoberfest participants, good to see you.

This issue's goal is to create a footer section of home page which also includes Navigation bar of farming webapp

Feel free to be creative! And please take care of the following criteria:

- create atleast 4 rows with Quick Links and Basic Footer Data
- Try and get the structure approved before making final pr.

How to get it approved?

- Add a screenshot of footer on this thread and wait for one of the mentors to get back to you.
- Once it's approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by codervivek5** [comment]
I want to work on this issue

**Comment by anj20** [comment]
hey ! @prathimacode-hub can u please assign this to me under hackoctoberfest?

**Comment by Isha307** [comment]
Yes, but one issue at a time.

**Comment by prathimacode-hub** [comment]
Issue assigned to @anj20

**Comment by sm9416220** [comment]
@Isha307 @prathimacode-hub Can you assign it to me!
I will use Html, css and boostrap for styling the footer section.

**Comment by prathimacode-hub** [comment]
I asked approach you would follow to be done as instructed. Issue assigned. @sm9416220

**Comment by prathimacode-hub** [comment]
It is fine for now. @sm9416220
