### ISSUE TITLE
FarmArk : Make FarmArk Logo and Favicon

### ISSUE THREAD

**Issue by prathimacode-hub** [prathimacode-hub/FarmArk#9]
Hey OpenCode participants, good to see you.

Feel free to be creative! And please take care of the following criteria:

- upload two versions of both logo and favicon-one with white bg and another with transparent bg.
- name the images semantically (e.g.: logo_bg, logo_wtbg, etc.)
Try and get your designs approved before making final pr.

How to get designs approved?
- Comment your designs on this thread and wait for one of the mentors to get back to you.
- Once your designs are approved, go ahead and make pr.

Please read [CONTRIBUTING.md](https://github.com/prathimacode-hub/FarmArk/blob/main/CONTRIBUTING.md) at least once before contributing code.

**Comment by aswinikalyan30** [comment]
Can i take this up as part of OpenCode? Shall present a sample design, and any changes if required can be made.

**Comment by prathimacode-hub** [comment]
Yup, go ahead. Issue assigned to @aswinikalyan30

**Comment by aswinikalyan30** [comment]
White bg:
![FarmArk (2)](https://user-images.githubusercontent.com/76677408/162623273-c060f5ca-99e3-47a3-8d96-248c52227d77.png)

Transparent BG:
![FarmArk (1)](https://user-images.githubusercontent.com/76677408/162623292-d5245a87-3f00-470b-aaa7-fc34f03704bb.png)


Hey, this is what i designed, please check and let me know

**Comment by prathimacode-hub** [comment]
Looks awesome. Instead of Orange, you can go with Brown branch for both White & Transparent Background. @aswinikalyan30

**Comment by aswinikalyan30** [comment]
Hey, if it's gonna be put against a black background using the transparent one, the brown isn't showing much.... which is why i made it orange

**Comment by prathimacode-hub** [comment]
Ok got you. Have you prepared the favicon as well? @aswinikalyan30

**Comment by aswinikalyan30** [comment]
![FarmArk (3)](https://user-images.githubusercontent.com/76677408/162666770-33107e72-87cf-4659-909b-757dd46c6b9b.png)

Can this be used as a favicon?

**Comment by prathimacode-hub** [comment]
Yes but size differs. Have to do changes accordingly. As mentioned in issue details, upload two versions of both logo and favicon-one with white bg and another with transparent bg. name the images semantically (e.g.: logo_bg, logo_wtbg, etc.)

So we totally get 4 images for logo and favicon. @aswinikalyan30

**Comment by aswinikalyan30** [comment]
Sure, will resize it accordingly and create a PR

**Comment by prathimacode-hub** [comment]
Yup go ahead @aswinikalyan30

**Comment by aswinikalyan30** [comment]
Do i add them in readme assets?

**Comment by prathimacode-hub** [comment]
No create a separate repository as "assets" @aswinikalyan30

**Comment by aswinikalyan30** [comment]
okay sure
